Dark Mode
diwash007/kurakani pull request #13
Opened 2023-10-07 13:59 UTC by KriteshTimsina

This pull request was done to implement dark mode using a next-themes package.

Key Changes:

Dark Mode
Auto-save dark mode

2023-10-07 16:05 UTC, diwash007 requested changes

2023-10-07 16:05 UTC, diwash007 commented on frontend/src/components/Chat/ChatFooter.tsx
> +          className="cursor-pointer absolute top-[6px] right-2 text-primary "
why extra space?

2023-10-07 16:05 UTC, diwash007 commented on frontend/src/components/Chat/ChatHeader.tsx
> +    <div className="basis-[7%] border-b-2 flex items-center justify-between p-3 font-medium ">
why extra space again?

2023-10-07 16:05 UTC, diwash007 commented on frontend/src/components/Room/RoomSideBar.tsx
> +      <div className="py-1 ">
again

2023-10-07 16:05 UTC, diwash007 commented on frontend/src/components/shared/DarkModeSwitch.tsx
> +      }
Wouldn't ref be better instead of state for checking if the component is mounted or not?

2023-10-07 16:05 UTC, diwash007 commented on frontend/src/contexts/Providers.tsx
> +      }
ref or state?

2023-10-07 16:05 UTC, diwash007 commented on frontend/tailwind.config.js
>    content: [
please format the files properly before comitting

2023-10-07 16:07 UTC, diwash007 commented
@KriteshTimsina please match the color of the dark toggles icon to the theme.

2023-10-07 16:07 UTC, diwash007 commented
I see the Sun icon is present when it is light and Moon when it is dark .. shouldn't it be alternate instead? just my opinion

2023-10-07 16:10 UTC, diwash007 commented
<img width="1437" alt="image" src="https://github.com/diwash007/kurakani/assets/39879720/7e92c029-8eb7-453c-92f8-eb29d864f015">
the separator lines could be grayish .. and overall white parts can be a little lighter shade of gray instead so that it doesn't strain the eyes

2023-10-08 01:49 UTC, KriteshTimsina commented
working on it !

2023-10-08 07:08 UTC, merged

2023-10-08 07:15 UTC, diwash007 commented
GG!