fix to the issue 21
diwash007/kurakani pull request #22
Opened 2023-10-27 15:28 UTC by WarlockJa

I have replaced roomUsers object in socket.js with UsersState to contain username data. On front-end modified RoomCard.tsx and /frontend/src/app/chat/[roomId]/page.tsx to work with the new UserState.

2023-10-27 15:57 UTC, diwash007 reviewed
Thank you so much for your contribution, @WarlockJa 
I see a lot of TODOs on the comments .. are these all done or yet to be done?
If already completed, please remove the redundant comments

2023-10-27 19:20 UTC, WarlockJa commented
Hello! Removed unnecessary comments.

2023-10-28 02:14 UTC, diwash007 commented
Thank you so much @WarlockJa 
I will review your commits tomorrow 
Have a great day!

2023-10-30 13:53 UTC, diwash007 requested changes

2023-10-30 13:53 UTC, diwash007 commented on backend/routes/socket.js
> +        `You have joined the ${roomId === "1" ? "Global" : roomId} chat room`,
<img width="480" alt="image" src="https://github.com/diwash007/kurakani/assets/39879720/d2e10972-1296-467c-9a75-56d347a6e9fa">

2023-10-30 13:53 UTC, diwash007 commented on backend/routes/socket.js
> +        `You have joined the ${roomId === "1" ? "Global" : roomId} chat room`,
while joining private room

2023-10-30 13:53 UTC, diwash007 commented on backend/routes/socket.js
> +        buildMsg(`${user.username} has joined the room`, roomId)
Can you please change the join and leave message to the following format?
`<username>` has joined
`<username>` has left
no need to specify the room name. + no need of "You" as well

2023-10-30 13:53 UTC, diwash007 commented on backend/routes/socket.js
> +const UsersState = {
can we please organize the state and functions into different specific files?
That way it will be more organized to checkout the code.

2023-10-31 07:05 UTC, WarlockJa commented
Hello! Removed notifications to the joining user. Shortened notification for joined/left users as described. Moved UserState and its function to a separate userState.js file.

2023-10-31 07:36 UTC, diwash007 commented
awesome work,
One last thing, Can you please make your commit title more descriptive?

2023-10-31 09:45 UTC, WarlockJa commented
Sure. What do you have in mind?

2023-10-31 16:13 UTC, merged